import { Verb } from "../types";

export const words: Verb[] = [
  ["arise", "arose", "arisen"],
  ["be", "was, were", "been"],
  ["bear", "bore", "borne, born"],
  ["beat", "beat", "beaten, beat"],
  ["become", "became", "become"],
  ["begin", "began", "begun"],
  ["bend", "bent", "bent"],
  ["bet", "bet, betted", "bet, betted"],
  ["bind", "bound", "bound"],
  ["bite", "bit", "bitten"],
  ["bleed", "bled", "bled"],
  ["bless", "blessed, blest", "blessed, blest"],
  ["blow", "blew", "blown"],
  ["break", "broke", "broken"],
  ["breed", "bred", "bred"],
  ["bring", "brought", "brought"],
  ["broadcast", "broadcast, broadcasted", "broadcast, broadcasted"],
  ["build", "built", "built"],
  ["burn", "burnt, burned", "burnt, burned"],
  ["burst", "burst", "burst"],
  ["bust", "bust, busted", "bust, busted"],
  ["buy", "bought", "bought"],
  ["catch", "caught", "caught"],
  ["choose", "chose", "chosen"],
  ["come", "came", "come"],
  ["cost", "cost", "cost"],
  ["creep", "crept", "crept"],
  ["crow", "crowed", "crew, crowed"],
  ["cut", "cut", "cut"],
  ["deal", "dealt", "dealt"],
  ["dig", "dug", "dug"],
  ["do", "did", "done"],
  ["draw", "drew", "drawn"],
  ["dream", "dreamt, dreamed", "dreamt, dreamed"],
  ["drink", "drank", "drunk"],
  ["drive", "drove", "driven"],
  ["eat", "ate", "eaten"],
  ["fall", "fell", "fallen"],
  ["feed", "fed", "fed"],
  ["feel", "felt", "felt"],
  ["fight", "fought", "fought"],
  ["find", "found", "found"],
  ["flee", "fled", "fled"],
  ["fling", "flung", "flung"],
  ["fly", "flew", "flown"],
  ["forbid", "forbad, forbade", "forbid, forbidden"],
  ["forecast", "forecast, forecasted", "forecast, forecasted"],
  ["forget", "forgot", "forgotten"],
  ["freeze", "froze", "frozen"],
  ["get", "got", "got, gotten"],
  ["give", "gave", "given"],
  ["go", "went", "gone"],
  ["grind", "ground", "ground"],
  ["grip", "gripped, gript", "gripped, gript"],
  ["grow", "grew", "grown"],
  ["hang", "hung", "hung"],
  ["have", "had", "had"],
  ["hear", "heard", "heard"],
  ["heave", "heaved, hove", "heaved, hove"],
  ["hide", "hid", "hidden, hid"],
  ["hit", "hit", "hit"],
  ["hold", "held", "held"],
  ["hurt", "hurt", "hurt"],
  ["keep", "kept", "kept"],
  ["kneel", "knelt, kneeled", "knelt, kneeled"],
  ["know", "knew", "known"],
  ["lay", "laid", "laid"],
  ["lead", "led", "led"],
  ["lean", "leant, leaned", "leant, leaned"],
  ["leap", "leapt, leaped", "leapt, leaped"],
  ["learn", "learnt, learned", "learnt, learned"],
  ["leave", "left", "left"],
  ["lend", "lent", "lent"],
  ["let", "let", "let"],
  ["lie", "lay", "lain"],
  ["light", "lit, lighted", "lit, lighted"],
  ["lose", "lost", "lost"],
  ["make", "made", "made"],
  ["mean", "meant", "meant"],
  ["meet", "met", "met"],
  ["pay", "paid", "paid"],
  ["put", "put", "put"],
  ["read", "read", "read"],
  ["rid", "rid, ridded", "rid, ridded"],
  ["ride", "rode", "ridden"],
  ["ring", "rang", "rung"],
  ["rise", "rose", "risen"],
  ["run", "ran", "run"],
  ["saw", "sawed", "sawn, sawed"],
  ["say", "said", "said"],
  ["see", "saw", "seen"],
  ["seek", "sought", "sought"],
  ["sell", "sold", "sold"],
  ["send", "sent", "sent"],
  ["set", "set", "set"],
  ["shake", "shook", "shaken"],
  ["shine", "shone", "shone"],
  ["shoot", "shot", "shot"],
  ["show", "showed", "shown, showed"],
  ["shred", "shred, shredded", "shred, shredded"],
  ["shrink", "shrank, shrunk", "shrunk"],
  ["shut", "shut", "shut"],
  ["sing", "sang", "sung"],
  ["sink", "sank", "sunk"],
  ["sit", "sat", "sat"],
  ["sleep", "slept", "slept"],
  ["slide", "slid", "slid"],
  ["smell", "smelt, smelled", "smelt, smelled"],
  ["speak", "spoke", "spoken"],
  ["spell", "spelt, spelled", "spelt, spelled"],
  ["spend", "spent", "spent"],
  ["spin", "spun", "spun"],
  ["spit", "spat", "spat"],
  ["split", "split", "split"],
  ["spread", "spread", "spread"],
  ["spring", "sprang, sprung", "sprung"],
  ["stand", "stood", "stood"],
  ["steal", "stole", "stolen"],
  ["stick", "stuck", "stuck"],
  ["sting", "stung", "stung"],
  ["strike", "struck", "struck"],
  ["swear", "swore", "sworn"],
  ["sweep", "swept", "swept"],
  ["swim", "swam", "swum"],
  ["swing", "swung", "swung"],
  ["take", "took", "taken"],
  ["teach", "taught", "taught"],
  ["tear", "tore", "torn"],
  ["tell", "told", "told"],
  ["think", "thought", "thought"],
  ["throw", "threw", "thrown"],
  ["thrust", "thrust", "thrust"],
  ["understand", "understood", "understood"],
  ["wake", "woke, waked", "woken, waked"],
  ["wear", "wore", "worn"],
  ["wed", "wed, wedded", "wed, wedded"],
  ["weep", "wept", "wept"],
  ["win", "won", "won"],
  ["wind", "wound", "wound"],
  ["write", "wrote", "written"],
];
