import clsx from "clsx";
import { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Checkbox from "../components/Checkbox";
import Game from "../components/Game";
import { Mode } from "../types";

const Home: NextPage = () => {
  const [start, setStart] = useState(false);

  const [mode, setMode] = useState<Mode>(Mode.infinite);

  const handleChangeMode = (mode: Mode) => {
    setMode(mode);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen h-screen bg-gray-800 text-gray-50">
        {start ? (
          <Game mode={mode} exit={() => setStart(false)} />
        ) : (
          <div className="flex flex-col items-center justify-center h-full">
            <div className="max-w-[320px] rounded bg-gray-700">
              <h1 className="p-4 px-6 text-xl font-bold">
                Learn irregular verbs
              </h1>
              <div className="w-full h-1 bg-gray-800"></div>
              <div className="flex flex-col p-4 mb-2">
                <p className="mb-2 font-bold opacity-80">Count words</p>
                <Checkbox
                  checked={Mode.infinite === mode}
                  onChange={() => handleChangeMode(Mode.infinite)}
                >
                  Infinite
                </Checkbox>
                <Checkbox
                  checked={Mode.fast === mode}
                  onChange={() => handleChangeMode(Mode.fast)}
                >
                  {Mode.fast}
                </Checkbox>
                <Checkbox
                  checked={Mode.middle === mode}
                  onChange={() => handleChangeMode(Mode.middle)}
                >
                  {Mode.middle}
                </Checkbox>
                <Checkbox
                  checked={Mode.long === mode}
                  onChange={() => handleChangeMode(Mode.long)}
                >
                  {Mode.long}
                </Checkbox>
              </div>
              <div className="w-full h-1 bg-gray-800"></div>

              <button
                onClick={() => setStart(true)}
                className="w-full py-2 bg-indigo-500 rounded rounded-t-none hover:opacity-80"
              >
                Start learn
              </button>
            </div>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
